#!/usr/bin/env python3
"""Generate the reduced-size IMDCT tables used by AAC_ENABLE_DECIM.

AACSetOutputDecimation(h, 2 or 4) runs the inverse transform at 1/2 or 1/4
size on the lowest 1/2 or 1/4 of the spectrum, which yields the band-limited
PCM directly at the lower rate (see imdct.c). That needs pre-twiddle, window
and bit-reverse tables for nmdct = 64/512 (half) and 32/256 (quarter). The
FFT twiddles (twidTabOdd/twidTabEven) and the PostMultiply table
(cos1sin1tab) already cover every size and are reused as they are.

The formulas are the ones documented in trigtabs.c. Run with --check to
confirm they reproduce the existing 128/1024 tables bit for bit (they do,
which is what makes the new sizes trustworthy), otherwise it prints the C
block that lives in trigtabs.c under #ifdef AAC_ENABLE_DECIM.

Pre-twiddle tables carry an extra factor of 1/decim: an nmdct/decim-point
DCT-IV is normalised by decim/nmdct, and the band-limited samples must match
the scale of the full-size transform's output.
"""
import math
import sys

SIZES = [(64, 2), (512, 2), (32, 4), (256, 4)]   # tabidx 2..5, in order


def q(x, bits):
    v = x * (1 << bits)
    v = int(math.floor(v + 0.5)) if v >= 0 else -int(math.floor(-v + 0.5))
    return min(v, 2**31 - 1)


def sin_window(n):
    out = []
    for i in range(n // 2):
        out.append(q(math.sin((i + 0.5) * math.pi / (2.0 * n)), 31))
        out.append(q(math.sin((n - 1 - i + 0.5) * math.pi / (2.0 * n)), 31))
    return out


def i0(x):
    x2, s, k, kf, xp = x / 2.0, 0.0, 0, 1.0, 1.0
    while True:
        last = s
        t = xp / kf
        s += t * t
        k += 1
        kf *= k
        xp *= x2
        if s == last:
            return s


def kbd_window(n):
    a = 6.0 if n <= 128 else 4.0    # short windows keep alpha 6, long alpha 4
    nref = 2 * n
    base = i0(math.pi * a)

    def w(k):
        t = (k - nref / 4.0) / (nref / 4.0)
        return i0(math.pi * a * math.sqrt(max(0.0, 1.0 - t * t))) / base
    wbase = sum(w(k) for k in range(nref // 2 + 1))
    ref, cur = [], 0.0
    for k in range(nref // 2):
        cur += w(k)
        ref.append(math.sqrt(cur / wbase))
    out = []
    for i in range(n // 2):
        out.append(q(ref[i], 31))
        out.append(q(ref[n - 1 - i], 31))
    return out


def premul(n, scale=1.0):
    out = []
    for i in range(n // 4):
        for a in ((i + 0.25) * math.pi / n, (n // 2 - 1 - i + 0.25) * math.pi / n):
            out.append(q(-(math.cos(a) + math.sin(a)) * scale, 30))
            out.append(q(-math.sin(a) * scale, 30))
    return out


def bitrev_table(nfft):
    nb = nfft.bit_length() - 1 - 2

    def rev(v):
        r = 0
        for _ in range(nb):
            r, v = (r << 1) | (v & 1), v >> 1
        return r
    out = []
    for i in range(1 << nb):
        if i < rev(i):
            out += [i, rev(i)]
    out += [i for i in range(1 << nb) if rev(i) == i]
    return out + [0]


def emit(name, ctype, data, fmt, per_line, sections, attr="PROGMEM"):
    print("const %s %s[%d] %s = {" % (ctype, name, len(data), attr))
    for label, start, count in sections:
        print("    /* %s */" % label)
        chunk = data[start:start + count]
        for i in range(0, len(chunk), per_line):
            print("    " + ", ".join(fmt % (v & 0xffffffff if ctype == "int" else v)
                                     for v in chunk[i:i + per_line]) + ",")
    print("};\n")


def offsets(lengths):
    out, pos = [], 0
    for n in lengths:
        out.append(pos)
        pos += n
    return out


def check():
    import re
    src = open("trigtabs.c").read()

    def table(name):
        body = re.search(name + r"\[[^\]]*\][^{]*\{(.*?)\};", src, re.S).group(1)
        body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
        vals = [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", body)]
        return [v - 2**32 if v >= 2**31 else v for v in vals]
    ok = True
    for name, gen in (("sinWindow", sin_window), ("kbdWindow", kbd_window),
                      ("cos4sin4tab", premul)):
        ref = table(name)
        mine = gen(128) + gen(1024)
        ok &= ref == mine
        print("%-12s %s" % (name, "match" if ref == mine else "MISMATCH"))
    ref = [v & 0xff for v in table("bitrevtab")]
    mine = bitrev_table(64) + bitrev_table(512)
    ok &= ref == mine
    print("%-12s %s" % ("bitrevtab", "match" if ref == mine else "MISMATCH"))
    return ok


def main():
    if "--check" in sys.argv:
        sys.exit(0 if check() else 1)
    lens = [n for n, _ in SIZES]
    print("/* generated by gen_decim_tabs.py - do not edit by hand */\n")
    print("const int decimTabOffset[NUM_DECIM_SIZES] DPROGMEM = {%s};\n"
          % ", ".join(str(v) for v in offsets(lens)))
    secs = []
    for (n, d), off in zip(SIZES, offsets(lens)):
        secs.append(("nmdct = %d (1/%d)" % (n, d), off, n))
    pre = []
    for n, d in SIZES:
        pre += premul(n, 1.0 / d)
    emit("cos4sin4tabDecim", "int", pre, "0x%08x", 8,
         [(s[0] + ", format = Q30 / decim", s[1], s[2]) for s in secs],
         "DPROGMEM")
    emit("sinWindowDecim", "int", sum((sin_window(n) for n, _ in SIZES), []),
         "0x%08x", 8, [(s[0] + ", format = Q31", s[1], s[2]) for s in secs])
    emit("kbdWindowDecim", "int", sum((kbd_window(n) for n, _ in SIZES), []),
         "0x%08x", 8, [(s[0] + ", format = Q31", s[1], s[2]) for s in secs])
    br = [bitrev_table(n // 2) for n, _ in SIZES]
    print("const int bitrevtabDecimOffset[NUM_DECIM_SIZES] DPROGMEM = {%s};\n"
          % ", ".join(str(v) for v in offsets(len(b) for b in br)))
    emit("bitrevtabDecim", "unsigned char", sum(br, []), "0x%02x", 16,
         [("nfft = %d" % (n // 2), o, len(b))
          for (n, _), o, b in zip(SIZES, offsets(len(b) for b in br), br)],
         "DPROGMEM")


if __name__ == "__main__":
    main()
